### ISSUE TITLE
GSLS optimizer crashing with QAOA default parameter bounds

### ISSUE THREAD

**Issue by dleidreiter** [qiskit-community/qiskit-algorithms#94]
### Environment

- **Qiskit Algorithms version**: 0.2.1
- **Python version**: 3.11.1
- **Operating system**: Windows 10

### What is happening?

When using the `GSLS` optimizer in combination with the `QAOA` minimum_eigensolver, the optimization crashes. This seems to stem from the GSLS optimizer not being capable of dealing with parameter bounds of the form `[(None, None)]`.

### How can we reproduce the issue?

The bug can be reproduced by trying to compute the minimum eigenvalue of a trivial hamiltonian:

```
from qiskit import Aer
from qiskit.primitives import BackendSampler
from qiskit.quantum_info import SparsePauliOp
from qiskit_algorithms.optimizers import GSLS
from qiskit_algorithms.minimum_eigensolvers import QAOA

backend = Aer.get_backend("aer_simulator")
sampler = BackendSampler(backend)

optimizer = GSLS()
qaoa = QAOA(optimizer=optimizer, sampler=sampler)

hamiltonian = SparsePauliOp(["ZI"])
result = qaoa.compute_minimum_eigenvalue(hamiltonian)
print(result)
```

This results in the following Traceback:

```
Traceback (most recent call last):
  File "C:\...\minimal_example.py", line 19, in <module>
    result = qaoa.compute_minimum_eigenvalue(hamiltonian)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\venv\Lib\site-packages\qiskit_algorithms\minimum_eigensolvers\sampling_vqe.py", line 218, in compute_minimum_eigenvalue
    optimizer_result = self.optimizer.minimize(
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\venv\Lib\site-packages\qiskit_algorithms\optimizers\gsls.py", line 125, in minimize
    x, fun, nfev, _ = self.ls_optimize(x0.size, fun, x0, var_lb, var_ub)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\venv\Lib\site-packages\qiskit_algorithms\optimizers\gsls.py", line 185, in ls_optimize
    directions, sample_set_x = self.sample_set(n, x, var_lb, var_ub, sample_set_size)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\venv\Lib\site-packages\qiskit_algorithms\optimizers\gsls.py", line 298, in sample_set
    if (points >= var_lb).all() and (points <= var_ub).all():
        ^^^^^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'float' and 'NoneType'
```

### What should happen?

I would expect the optimization process to finish without crashing and to print the final result.

**Comment by woodsp-ibm** [comment]
Just an FYI having run your sample to check it now runs with the fix - Qiskit Aer has its own primitives https://qiskit.org/ecosystem/aer/apidocs/aer_primitives.html which are more efficient/better to use than using the BackendSampler/Estimator that were more intended for providers that did not have primitives for their backends.

**Comment by dleidreiter** [comment]
Ok, thank you. :)
